const { buildSync } = require('esbuild')
const { spawnSync } = require('node:child_process')
const path = require('node:path')
const root = path.resolve(__dirname, '..')
let result = spawnSync('cargo', ['build', '--manifest-path', 'src-tauri/Cargo.toml', '--example', 'parity'], { cwd: root, stdio: 'inherit' })
if (result.status !== 0) process.exit(result.status ?? 1)
buildSync({ entryPoints: [path.join(root, 'tests/rust-parity.ts')], outfile: path.join(root, '.test-out/parity.cjs'), bundle: true, platform: 'node', format: 'cjs' })
result = spawnSync(process.execPath, [path.join(root, '.test-out/parity.cjs')], { cwd: root, stdio: 'inherit' })
process.exit(result.status ?? 1)
